package(default_visibility = ["//visibility:public"])

test_suite(
    name = "coverage_tests",
    tests = [
        "//src/test/java/org/ariake/config:config_test",
        "//src/test/java/org/ariake/jpa/eclipselink:eclipselink_jpa_test",
        "//src/test/java/org/ariake/metrics:metrics_api_test",
        "//src/test/java/org/ariake/metrics/prometheus:prometheus_metrics_test",
        "//src/test/java/org/ariake/server:server_test",
        "//src/test/java/org/ariake/tx/narayana:narayana_tx_test",
    ],
)
